### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by vitalygoji** [PolymerElements/iron-flex-layout#127]
When I replaced older version with new one to avoid deprecation /deep/ issue
a)It could not find files and directories (???!!!)
b)After I created dir and moved files around to adjust new file structure(??!!)  it broke slider and date chooser.
I had to revert to older version. Is there an easy way to  get rid of deprecation /deep/ warnings?

**Comment by notwaldorf** [comment]
Now sure what the a) point means, and without repro steps, I don't know how to answer it. Maybe your update didn't work correctly? Did you run `bower install` correctly? Nothing should have changed in the directory structure.

I also don't know what b) means, because if you moved the code to an incorrect location, it will obviously not work.

Closing, as there are no repro steps to understand what's going on
