### ISSUE TITLE
 /deep/ and other piercing combinators are depricated

### ISSUE THREAD

**Issue by moderndeveloperllc** [PolymerElements/iron-flex-layout#23]
Just a placeholder for now I guess, but the /deep/ combinator is currently deprecated, and it looks like piecing combinators [are on the way out too](https://www.w3.org/wiki/Webapps/WebComponentsApril2015Meeting)

https://www.chromestatus.com/features/6750456638341120
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/68qSZM5QMRQ/pT2YCqZSomAJ

This means iron-shadow-flex-layout.html will need to be rewritten.

**Comment by SmokyBob** [comment]
There is a [cool branch](https://github.com/PolymerElements/iron-flex-layout/tree/no-deep) with classes using custom properties

**Comment by gazal-k** [comment]
Was this [cool branch](https://github.com/PolymerElements/iron-flex-layout/tree/no-deep) already merged? and is iron-shadow-flex-layout.html just maintained for backward compatibility?

**Comment by notwaldorf** [comment]
That branch has not been merged yet, and will probably not be merged in its current form. I'm working on removing `/deep/` this week, so stay tuned. Hopefully it won't break anything :)

**Comment by gazal-k** [comment]
@notwaldorf :+1: can you please share what the alternative is to using `/deep/` for layout classes?

**Comment by notwaldorf** [comment]
@gazal-k I think the plan is to: 1. make the `/deep/` part go away altogether (with a nice deprecation message), so the classes, like the mixin equivalents, will only work on the context they're applied to. 2. make more granular imports for the classes versions, so that you don't have to pull *all* of `iron-flex-layout` to just get the plain flex box layout-y things.

**Comment by MetaMemoryT** [comment]
:+1: interested in this

other elements:

https://github.com/PolymerElements/paper-styles/issues/49

**Comment by MetaMemoryT** [comment]
Any progress update?

**Comment by notwaldorf** [comment]
@MetaMemoryT We have started cleaning up all our elements and demos first to make sure they are no longer using the `/deep/` version of the styles. For now, our recommendation is to use the mixin version of all the flex layout styles and paper-styles.

**Comment by ebidel** [comment]
@notwaldorf is the plan to just get rid of the the /deep/ import [here](https://github.com/PolymerElements/iron-flex-layout/blob/master/classes/iron-flex-layout.html#L11)? That would allow any element needing the classes to still import it, but they wouldn't get the /deep/ versions. 

For codelabs, we get rid of the `/deep/` console warnings by vulcanizing out `iron-shadow-flex-layout.html` from our build:

```
    .pipe($.vulcanize({
        ...
        stripExcludes: [
          'iron-shadow-flex-layout.html'
        ]
      }))
```

**Comment by MetaMemoryT** [comment]
thanks @ebidel for suggestion
deleting the import [here](https://github.com/PolymerElements/iron-flex-layout/blob/master/classes/iron-flex-layout.html#L11) worked for me.

**Comment by urandom** [comment]
I've personally created a style module with the full contents of the layout classes in it (can't include the classes html, since it auto imports the flex part for some reason), and used it as described in https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules .It might be a good idea for such a style module to be provided out of the box, so that people don't have to do it themselves, and can still stay on classes

**Comment by notwaldorf** [comment]
For anyone who wants to follow along, I have a PR open (https://github.com/PolymerElements/iron-flex-layout/pull/32) that should fix this. Fingers crossed I get to it this week :)

**Comment by robrez** [comment]
I'm interested in opinions about creating a [style module](https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules) for iron-flex-layout?

I've been working on a decent-sized app that uses lots of custom-elements. Almost all of my initial coding utilized styling that worked because of /deep/. I'm finding that I've been inconsistent in refactoring my elements to utilize iron-flex mixins. For example, overlooking a usage of a /deep/ className here-or-there. I've also been repeating myself a lot.. eg: copying an identical css rule around to multiple elements.

If there were a style mode, my existing code would continue to function so long as I included the style module.

I was going to create a style module that imported iron-flex-layout and had rules that match `classes/iron-flex-layout` except that they `@apply(--corresponding-mixin)`.

**Comment by notwaldorf** [comment]
@robrez Does the PR I have work for you? We went with copying the rules, rather than `@applies` because it's a little bit faster (less work Polymer has to do)

**Comment by robrez** [comment]
Yep looks great to me!

**Comment by bastienarm** [comment]
@notwaldorf just a little question after updating iron-flex-layout from 1.2.2 to 1.3.1 to resolve to /deep/ warning.

Change the include of 
```html
<link rel="import" href="../bower_components/iron-flex-layout/classes/iron-flex-layout.html">
```
to 
```html
<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout-classes.html">
```
to be sure to use the good file.

It seems that the "fullbleed" class on the body no longer exists, so I just add 
```css
body  {
 margin: 0;
 height: 1000vh;
}
```
into my css (without this, the body will only have the minimum height required), and set the html to
```html
<body unresolved class="layout vertical"></body>
```

The question is, am I right to do things like this or not?

Thanks !
