### ISSUE TITLE
scrolling horizontal layout not working in Polymer-Starter-kit in phonegap/cordova webview

### ISSUE THREAD

**Issue by mojtabashabani** [PolymerElements/iron-flex-layout#25]
there is a problem with scrolling in horizontal div in starter kit , everything in chrome windows and android is fine , but scrolling not working in phonegap/cordova webview
```
<div id="Mainlist1" class="layout horizontal scroll" >
                        <paper-material>Item 1</paper-material>
                        <paper-material>Item 2</paper-material>
                        <paper-material>Item 3</paper-material>
                        <paper-material>Item 4</paper-material>
                        <paper-material>Item 5</paper-material>
                        <paper-material>Item 6</paper-material>
                        <paper-material>Item 7</paper-material>
                        <paper-material>Item 8</paper-material>
                        <paper-material>Item 9</paper-material>
 </div>
```
solution?

**Comment by notwaldorf** [comment]
@addyosmani tentatively assigning this to you since it says "polymer starter kit" :)

**Comment by notwaldorf** [comment]
Sorry for dropping the ball on this issue! I'm going to close this, since it's super old and it doesn't have any repro steps. However, if you're still having problems with this, would you might putting together a jsbin (sample to get you started: http://jsbin.com/todowe/edit?html,output) about what you're expecting to see, and what is actually happening?

Thanks!
