### ISSUE TITLE
Hidden attribute overriden when using class .layout

### ISSUE THREAD

**Issue by edgarshurtado** [PolymerElements/iron-flex-layout#91]
### Description

When using iron-flex class, in case you use `.layout .horizontal` or `.layout .vertical`, the hidden attribute is ignored.

I've realised that `.layout` overrides the `display:none` of the hidden attribute to `display:flex`.

I've also realised that if you import the iron-flex-layout class **iron-positioning** it sets : `[hidden]{display: none !important;}` so the hidden attribute works properly.

### Expected outcome
The dom element to be hidden if you set the hidden attribute to it without having to include **iron-positioning**

### Actual outcome
The dom element is displayed 

### Live Demo

I've created this [JSbin](https://jsbin.com/keteduvozu/edit?html,output) that allows to reproduce it. 

### Steps to reproduce
1. Include **iron-flex** class to your element style
2. Set some dom element to hidden and add to it the classes `.layout .horizontal` or `.layout .vertical`
3. If you import the class **iron-positioning** works fine

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9

(Not tested in the browsers below)
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
The `hidden` attribute does not do that natively: http://jsbin.com/vekufib/edit?html,output. Basically, even with plain divs, the moment you set a `display` style on an element, `hidden` does not work (because it has the lowest specificity, and loses to the `display: block` style. To fix this, you _have_ to add a `[hidden] { display: none;}` style

`iron-flex-positioning` actually defines this style for you, which is why it works: https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout-classes.html#L368. If you don't want to use this, then you need to define a `hidden` style yourself.

Closing, as this is working correctly.

**Comment by edgarshurtado** [comment]
Oh, ok. I thought attributes where applied always over css styling. Thank you for the insight =).

Nevertheless, I think it could be beneficial for developers to point this out in the documentation of iron-flex-layout, or maybe add the `[hidden]{display: none;}` rule to the iron-flex class. Maybe I've been the only one who struggled with this, but it took me a while to figure out what was going on.

Again, thanks for your kind explanation.
